name: build

on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - development

jobs:
  v4-net-framework:
    runs-on: windows-2019
    steps:
      - name: Install Windows 8.1 SDK
        shell: powershell
        run: |
          Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
          Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
      - uses: actions/checkout@v1
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
      - name: Setup MSBuild
        uses: microsoft/Setup-MSBuild@v1
      - name: Restore nuget packages
        run: nuget restore DICOM.Desktop.sln
      - name: Build Desktop platform
        run: msbuild DICOM.Desktop.sln -target:"Platform\DICOM_Desktop" -p:Configuration=Release -p:Platform="Any CPU" -maxCpuCount
      - name: Build tests for Desktop platform
        run: msbuild DICOM.Desktop.sln -target:"Unit Tests\DICOM_Tests_Desktop" -p:Configuration=Release -p:Platform="Any CPU" -maxCpuCount
      - name: Run tests for Desktop platform
        run: ./packages/xunit.runner.console.2.4.1/tools/net472/xunit.console.exe "Tests\Desktop\bin\Release\DICOM [Unit Tests].dll"

  v5-net-framework-462:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: '3.1.x'
    - name: Build
      run: dotnet build ./FO-DICOM.Core/FO-DICOM.Core.csproj --configuration Release --framework net462
    - name: Test
      run: dotnet test ./Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj --configuration Release --framework net462
      
  v5-net-core-21:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: '2.1.x'
    - name: Build
      run: dotnet build ./FO-DICOM.Core/FO-DICOM.Core.csproj --configuration Release --framework netstandard2.0
    - name: Test
      run: dotnet test ./Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj --configuration Release --framework netcoreapp2.1
      
  v5-net-core-31:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: '3.1.x'
    - name: Build
      run: dotnet build ./FO-DICOM.Core/FO-DICOM.Core.csproj --configuration Release --framework netstandard2.1
    - name: Test
      run: dotnet test ./Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj --configuration Release --framework netcoreapp3.1
      
