name: build

on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - development

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019] #, ubuntu-18.04, macOS-latest]
        dotnet-version: [2.1.803]

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build solution
      run: dotnet build ./FO-DICOM.Core/FO-DICOM.Core.csproj --configuration Release
      
    - name: Run tests on .NET Core
      run: dotnet test ./Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj --configuration Release --framework netcoreapp2.1
    
    - name: Run tests on .NET Framework
      run: dotnet test ./Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj --configuration Release --framework net461
      if: matrix.os == 'windows-2019'
