name: build

on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - development

jobs:
  checkout:
    runs-on: windows-2019
    steps:
        - uses: actions/checkout@v1
  setup-dotnet:
    runs-on: windows-2019
    steps:
        - uses: actions/setup-dotnet@v1 
          with:
            dotnet-version: '3.1.x'
  build:
    needs: [checkout, setup-dotnet]
    runs-on: windows-2019
    steps:
    - name: Build
      run: dotnet build ./FO-DICOM.Core/FO-DICOM.Core.csproj --configuration Release
  test:
    runs-on: windows-2019
    needs: build
    strategy:
      matrix:
        framework: ['netcoreapp2.1', 'netcoreapp3.1', 'net462']
    steps:
    - name: Test
      run: dotnet test ./Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj --configuration Release --framework ${{ matrix.framework }}
